apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-master
  namespace: qcast
  labels:
    app: rabbitmq
    role: master
    tier: backend
spec:
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
    role: master
    tier: backend
